/**
 * Domain contracts for the offline mission loop.
 *
 * Missions intentionally consume a small, renderer-independent event shape.
 * The match runtime can therefore feed this module from either the live
 * simulation or a deterministic test without introducing a clock, storage,
 * Three.js, or UI dependency.
 */

export const MISSION_STATE_VERSION = 1 as const;

export type MissionScope = "daily" | "weekly" | "match";

/** Values that can be measured from a completed local match. */
export type MissionMetric =
  | "matchesPlayed"
  | "wins"
  | "draws"
  | "losses"
  | "goals"
  | "shots"
  | "completedPasses"
  | "tackles";

export type MatchOutcome = "win" | "draw" | "loss";

export type MissionReward = {
  coins: number;
  xp: number;
};

/** A declarative mission template. Templates are not mutated while tracking. */
export type MissionDefinition = {
  /** Stable id used in save files and telemetry. */
  id: string;
  scope: MissionScope;
  title: string;
  description?: string;
  metric: MissionMetric;
  target: number;
  reward: MissionReward;
  /** When present, only completed matches in this mode contribute. */
  modeId?: string;
  /** When present, only this result contributes. */
  outcome?: MatchOutcome;
};

/**
 * The only event currently required by the mission domain. Values are for the
 * player's team; callers decide that mapping before dispatching the event.
 */
export type MatchCompletedEvent = {
  type: "matchCompleted";
  matchId: string;
  /** Epoch milliseconds (or another finite caller-owned timestamp). */
  occurredAt: number;
  outcome: MatchOutcome;
  modeId: string;
  goals: number;
  shots: number;
  completedPasses: number;
  tackles: number;
};

export type MissionEvent = MatchCompletedEvent;

/**
 * Period keys are deliberately supplied by the caller. They may be local
 * calendar keys (for example 2026-09-11 and 2026-W37), UTC keys, or a product
 * defined timezone key. This module never reads Date.now() or the host
 * timezone.
 */
export type MissionPeriodKeys = {
  dayKey: string;
  weekKey: string;
};

/** Aliases accepted by convenience APIs when integrating another time service. */
export type MissionPeriodInput = {
  dayKey?: string;
  weekKey?: string;
  dailyKey?: string;
  weeklyKey?: string;
};

/** Serializable snapshot of one mission instance. */
export type MissionProgress = {
  /** Stable period/match-specific id, suitable as a UI key. */
  instanceId: string;
  /** Template id. */
  missionId: string;
  scope: MissionScope;
  /** dayKey, weekKey, or matchId depending on scope. */
  periodKey: string;
  /** Present for per-match objectives. */
  matchId: string | null;
  title: string;
  description: string;
  metric: MissionMetric;
  target: number;
  progress: number;
  completed: boolean;
  claimed: boolean;
  /** Stable exactly-once credit key. Assigned when the mission is claimed. */
  claimId: string | null;
  reward: MissionReward;
  /** Conditions are snapshotted so an old save remains understandable. */
  modeId: string | null;
  outcome: MatchOutcome | null;
  /** Event timestamp, not generated by this module. */
  lastUpdatedAt: number | null;
  completedAt: number | null;
  /** Optional caller-supplied claim timestamp. */
  claimedAt: number | null;
};

/** Versioned JSON-safe state. No Set, Map, Date, or class instances are used. */
export type MissionState = {
  version: typeof MISSION_STATE_VERSION;
  dayKey: string;
  weekKey: string;
  missions: MissionProgress[];
  /** Kept forever in the offline save so replaying a match cannot pay twice. */
  processedMatchIds: string[];
};

export type MissionSystemOptions = {
  definitions?: readonly MissionDefinition[];
  state?: MissionState | string | unknown;
  /** Alias for state, useful for callers naming their initial snapshot. */
  initialState?: MissionState | string | unknown;
  periodKeys?: MissionPeriodInput;
};

export type MissionEventResult = {
  state: MissionState;
  accepted: boolean;
  /** True when matchId was already processed and no progress changed. */
  duplicate: boolean;
  /** True only when this call newly added matchId to processedMatchIds. */
  processed: boolean;
  changed: boolean;
  updatedMissionIds: string[];
  newlyCompletedMissionIds: string[];
  reason?: "invalid-event" | "duplicate";
};

export type MissionClaimOptions = {
  /** Optional caller-owned timestamp; no timestamp is generated by the domain. */
  claimedAt?: number;
};

export type MissionClaimStatus = "claimed" | "alreadyClaimed" | "notComplete" | "notFound";

/**
 * Result of an explicit claim attempt. `claimId`/`transactionId` are stable for
 * every known mission, including retries that return alreadyClaimed or
 * notComplete. A caller should credit coins/xp only for status === "claimed".
 */
export type MissionClaimResult = {
  state: MissionState;
  status: MissionClaimStatus;
  claimed: boolean;
  alreadyClaimed: boolean;
  claimId: string | null;
  /** Alias for integrations that call their external credit key a transaction. */
  transactionId: string | null;
  missionId: string | null;
  instanceId: string | null;
  reward: MissionReward;
  coins: number;
  xp: number;
  reason?: "not-found" | "not-complete" | "already-claimed";
};

export type MissionListOptions = {
  scope?: MissionScope;
  currentOnly?: boolean;
  dayKey?: string;
  weekKey?: string;
  matchId?: string;
};
