import type { PlayerAttributes, PlayerCard } from "../management/types";

/** The only schema version written by the progression store. */
export const PROGRESSION_STATE_VERSION = 1 as const;

export type ProgressionStateVersion = typeof PROGRESSION_STATE_VERSION;

export type MatchOutcome = "win" | "draw" | "loss";

/** Match telemetry used by the deterministic reward calculator. */
export type MatchPerformance = {
  goals: number;
  shots: number;
  completedPasses: number;
  tackles: number;
  possessionPercent: number;
};

/** The stable match boundary shared by Quick Match and future game modes. */
export type MatchRewardInput = {
  /** An opaque id generated by the match/mode owner. It is never parsed. */
  matchId: string;
  /** A caller-owned mode id, such as "quick-match" or "season". */
  modeId: string;
  outcome: MatchOutcome;
  performance: MatchPerformance;
};

/** A calculated reward is pure data and is safe to show before settlement. */
export type MatchReward = {
  matchId: string;
  modeId: string;
  outcome: MatchOutcome;
  performance: MatchPerformance;
  baseCoins: number;
  baseXp: number;
  performanceBonus: number;
  performanceBonusCoins: number;
  performanceBonusXp: number;
  coins: number;
  xp: number;
};

export type PlayerAttributeKey = keyof PlayerAttributes;

/** Persisted progression for one card. Attribute boosts are additive. */
export type CardProgress = {
  xp: number;
  level: number;
  upgrades: number;
  attributeBoosts: PlayerAttributes;
};

/** The result kept for a settled match, including the exact reward granted. */
export type SettledMatch = {
  matchId: string;
  modeId: string;
  outcome: MatchOutcome;
  reward: MatchReward;
  cardId?: string;
  cardXpAwarded?: number;
};

/** A reward from a mission, season, tournament, or another local subsystem. */
export type RewardCreditInput = {
  /** Stable caller-owned transaction id. Reusing it is intentionally idempotent. */
  transactionId: string;
  coins: number;
  xp: number;
  source?: string;
  cardId?: string;
};

export type CreditedReward = {
  transactionId: string;
  coins: number;
  xp: number;
  source?: string;
  cardId?: string;
};

/** Versioned, JSON-safe state. The ids arrays make idempotency/auditing explicit. */
export type ProgressionState = {
  version: ProgressionStateVersion;
  coins: number;
  totalXp: number;
  cards: Record<string, CardProgress>;
  settledMatches: Record<string, SettledMatch>;
  settledMatchIds: string[];
  creditedRewards: Record<string, CreditedReward>;
  creditedRewardIds: string[];
};

export type ProgressionPersistenceCode =
  | "malformed"
  | "migration"
  | "read-failed"
  | "write-failed"
  | "quota";

export type ProgressionPersistenceDiagnostic = {
  code: ProgressionPersistenceCode;
  message: string;
  recoverable: boolean;
};

/**
 * Deliberately smaller than the DOM Storage interface. A plain Map-backed
 * adapter, SSR shim, or test double can implement this contract.
 */
export type StorageLike = {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
};

export type SettlementOptions = {
  /** If present, this card receives the match XP in addition to totalXp. */
  cardId?: string;
  /** Overrides the card XP amount; defaults to the match reward XP. */
  cardXp?: number;
};

export type SettlementStatus = "applied" | "already-settled" | "invalid";

export type SettlementResult = {
  status: SettlementStatus;
  applied: boolean;
  alreadySettled: boolean;
  /** True when a duplicate id was submitted with different match data. */
  conflict: boolean;
  reason?: "invalid-match-id";
  reward: MatchReward;
  settledMatch?: SettledMatch;
  state: ProgressionState;
};

export type RewardCreditStatus = "applied" | "already-credited" | "invalid";

export type RewardCreditResult = {
  status: RewardCreditStatus;
  applied: boolean;
  alreadyCredited: boolean;
  reason?: "invalid-transaction-id" | "invalid-reward";
  credit: CreditedReward;
  state: ProgressionState;
};

export type UpgradeAttribute = PlayerAttributeKey | "all";

export type UpgradeQuoteOptions = {
  attribute?: UpgradeAttribute;
};

export type UpgradeQuote = {
  cardId: string;
  attribute: UpgradeAttribute;
  boost: number;
  boosts: PlayerAttributes;
  cost: number;
  currentLevel: number;
  currentUpgrades: number;
  nextLevel: number;
  confirmationToken: string;
  requiresConfirmation: true;
};

export type UpgradeConfirmation = {
  confirmed: boolean;
  confirmationToken?: string;
  expectedCost?: number;
};

export type UpgradeResultStatus =
  | "applied"
  | "confirmation-required"
  | "insufficient-funds"
  | "stale-quote"
  | "unknown-card"
  | "max-upgrades";

export type UpgradeResult = {
  status: UpgradeResultStatus;
  applied: boolean;
  reason?: UpgradeResultStatus;
  cardId: string;
  cost: number;
  quote: UpgradeQuote;
  progress: CardProgress;
  card?: PlayerCard;
  state: ProgressionState;
};

export type ProgressionStatePatch = Partial<Pick<ProgressionState, "coins" | "totalXp">>;

export type ProgressionStoreListener = (snapshot: ProgressionState, revision: number) => void;

export type CreateProgressionStoreOptions = {
  storage?: StorageLike;
  /** Deliberately distinct from DEFAULT_SQUAD_STORAGE_KEY. */
  key?: string;
  initialCoins?: number;
  initialXp?: number;
  initialState?: unknown;
};

export type ProgressionStore = {
  readonly snapshot: ProgressionState;
  readonly state: ProgressionState;
  readonly revision: number;
  readonly serialized: string;
  readonly diagnostics: readonly ProgressionPersistenceDiagnostic[];
  readonly persistenceDiagnostics: readonly ProgressionPersistenceDiagnostic[];
  readonly diagnosticMessages: readonly string[];
  getDiagnostics(): ProgressionPersistenceDiagnostic[];
  settleMatch(input: MatchRewardInput, options?: SettlementOptions): SettlementResult;
  /** Alias for adapters that call the operation settle. */
  settle(input: MatchRewardInput, options?: SettlementOptions): SettlementResult;
  creditReward(input: RewardCreditInput): RewardCreditResult;
  /** Alias used by mission/season adapters. */
  creditExternalReward(input: RewardCreditInput): RewardCreditResult;
  awardCardXp(cardId: string, amount: number): ProgressionState;
  addCardXp(cardId: string, amount: number): ProgressionState;
  getCardProgress(cardId: string): CardProgress;
  quoteUpgrade(cardId: string, options?: UpgradeQuoteOptions, card?: PlayerCard): UpgradeQuote;
  upgradeCard(
    cardId: string,
    confirmation: UpgradeConfirmation,
    options?: UpgradeQuoteOptions,
    card?: PlayerCard
  ): UpgradeResult;
  purchaseUpgrade(
    cardId: string,
    confirmation: UpgradeConfirmation,
    options?: UpgradeQuoteOptions,
    card?: PlayerCard
  ): UpgradeResult;
  update(change: ProgressionStatePatch | ((draft: ProgressionState) => void | ProgressionStatePatch)): ProgressionState;
  reset(): ProgressionState;
  save(): ProgressionState;
  persist(): ProgressionState;
  subscribe(listener: ProgressionStoreListener): () => void;
};

export type { PlayerAttributes, PlayerCard };
